version: '3'
services:
  trino:
    image: trinodb/trino
    container_name: trino
    environment:
      AWS_ACCESS_KEY: minio
      AWS_SECRET_KEY: minio1234
      S3_ENDPOINT: http://minio:9000
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/etc/trino

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data

